---
title: "EmpowerX"
date: "(`r Sys.Date()`)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: yeti
    source_code: embed
runtime: shiny
---

```{r initial_setup}
# LIBRARIES ######################################
# rendering
library("flexdashboard")
library("shiny")
library("DT")
# data I/O
library("googlesheets4")
# data manipulation
library("tidyverse")
library("magrittr")
library("dplyr")
library("stringr")

# IMPORT DATA FROM GOOGLE SHEETS #################

gs4_deauth()
cc <- read_sheet("https://docs.google.com/spreadsheets/d/1Scnezau55S2MUUsUlRE21wTWgDEQCWLg9BqJVw7pqo8/edit?usp=sharing", sheet = 4)

pr <- read_sheet("https://docs.google.com/spreadsheets/d/1Scnezau55S2MUUsUlRE21wTWgDEQCWLg9BqJVw7pqo8/edit?usp=sharing", sheet = 5)

# FUNCTIONS ######################################

# extract details, requirements, course categories
program_extract <- function(extract, nature, input) {
    temp <- data.frame(str_split(as.character(
        filter(pr[extract], pr[2] == nature , pr[1] == input)), "\n"))
    names(temp) <- names(pr[extract])
    temp
}

# extract credit/course distribution
program_extract_distribution <- function(nature, input) {
    temp <- data.frame(
        credit <- unlist(str_split(as.character(
            filter(pr[8:10], pr[2] == nature, pr[1] == input)), "\n")),
        course <- unlist(str_split(as.character(
            filter(pr[11:13], pr[2] == nature, pr[1] == input)), "\n")),
        row.names = c("Total", "Core", "Elective")
        )
    names(temp) <- c("Credits", "Courses")
    temp
}

# extract core/elective courses
program_extract_courses <- function(co6el7, nature, input) {
    cc %>% select(-detail) %>% filter(code %in% 
                                          unlist(str_split(as.character(
                                              filter(pr[co6el7], pr[2] == nature, pr[1] == input)), "\n")))
}
```

<!------------------------------------------------------------------------------------------------->

Courses
============

column{.sidebar data-width=350}
------------
### Filter Courses

Delete courses from search bar to remove them from search and enter courses into search bar to add them to search.


To search using keywords, use the search bar on the top right.

```{r input_courses}
# search bar for choosing departments
selectizeInput(
  inputId = "dept",
  label = "Department",
  multiple = TRUE,
  choices = unique(cc$dept),
  selected = unique(cc$dept),
)

# reset button for departments
actionButton(inputId = "reset_dept", label = "Reset Courses")

# reset departments
observeEvent(input$reset_dept, {
    updateSelectizeInput(inputId = "dept", label = "Department", selected = unique(cc$dept))
})

# search bar for choosing credits
selectizeInput(
  inputId = "credit",
  label = "Credits",
  multiple = TRUE,
  choices = unique(cc$credit),
  selected = unique(cc$credit),
)

# reset button for credits
actionButton(inputId = "reset_credit", label = "Reset Credits")

# reset credits
observeEvent(input$reset_credit, {
    updateSelectizeInput(inputId = "credit", label = "Credits", selected = unique(cc$credit))
})

# search bar for choosing prereq
selectizeInput(
  inputId = "prereq",
  label = "Prerequisite",
  multiple = FALSE,
  choices = c("None", unique(cc$code)),
  selected = "None",
)

# reset button for prereq
actionButton(inputId = "reset_prereq", label = "Reset Prerequisite")

# reset prereq
observeEvent(input$reset_prereq, {
    updateSelectizeInput(inputId = "prereq", label = "Prerequisite", selected = "None")
})

# search bar for choosing crosslist
selectizeInput(
  inputId = "crosslist_code",
  label = "Crosslitsted Course Code",
  multiple = FALSE,
  choices = c("None", unique(cc$code)),
  selected = "None",
)

# reset button for crosslist
actionButton(inputId = "reset_crosslist_code", label = "Reset Crosslisted Course Code")

# reset crosslist
observeEvent(input$reset_crosslist_code, {
    updateSelectizeInput(inputId = "crosslist_code", label = "Crosslitsted Course Code", selected = "None")
})
```

column{data-width=450}
------------
### Courses 

```{r output_courses}
# filter courses using inputs
course_table <- reactive(cc %>%
                             filter(dept %in% input$dept) %>% 
                             filter(credit %in% input$credit) %>%
                             {if(input$prereq != "None") filter(., str_detect(prereq, input$prereq)) else .} %>%
                             {if(input$crosslist_code != "None") filter(., str_detect(crosslist_code, input$crosslist_code)) else .} 
)

# render the final data table
renderDT(datatable(course_table(), 
                   rownames = FALSE, 
                   colnames = c("Department", "Code", "Title", "Credit", "Detail", "Prerequisite", "Crosslisted Courses"),
                   options = list(
                       scrollY = "200px",
                       autoWidth = TRUE,
                       columnDefs = list(
                           list(width = '50px', targets = c(0)),
                           list(width = '75px', targets = c(1,5,6)),
                           list(width = '50px', targets = c(3)),
                           list(width = '175px', targets = c(2)),
                           list(width = '500px', targets = c(4)),
                           list(className = 'dt-center', targets = c(0,1,3,6))
                           )
                       )
                   ) %>% formatStyle(c('dept','code'), fontWeight = 'bold')
)
```

<!------------------------------------------------------------------------------------------------->

Programs
===========

column{.sidebar data-width=350}
------------
### Search

Choose only one program at a time

```{r}
# search bar for choosing degree
selectizeInput(
  inputId = "degree",
  label = "Degree",
  multiple = FALSE,
  choices = c("None", filter(pr[1], pr[2] == "degree")),
  selected = "None",
)

# search bar for choosing major
selectizeInput(
  inputId = "major",
  label = "Major",
  multiple = FALSE,
  choices = c("None", filter(pr[1], pr[2] == "major")),
  selected = "None",
)

# search bar for choosing minor
selectizeInput(
  inputId = "minor",
  label = "Minor",
  multiple = FALSE,
  choices = c("None", filter(pr[1], pr[2] == "minor")),
  selected = "None",
)

# search bar for choosing specialization
selectizeInput(
  inputId = "specialization",
  label = "Specialization",
  multiple = FALSE,
  choices = c("None", filter(pr[1], pr[2] == "specialization")),
  selected = "None",
)

# search bar for choosing certification
selectizeInput(
  inputId = "certification",
  label = "Certification",
  multiple = FALSE,
  choices = c("None", filter(pr[1], pr[2] == "certification")),
  selected = "None",
)

# reset button for programs
actionButton(inputId = "reset_programs", label = "Reset")

# reset programs
observeEvent(input$reset_programs, {
    updateSelectizeInput(inputId = "degree", label = "Degree", selected = "None")
    updateSelectizeInput(inputId = "major", label = "Major", selected = "None")
    updateSelectizeInput(inputId = "minor", label = "Minor", selected = "None")
    updateSelectizeInput(inputId = "specialization", label = "Specialization", selected = "None")
    updateSelectizeInput(inputId = "certification", label = "Certification", selected = "None")
})

```

row{data-width=300}
------------

### Program details 
```{r}
table_prog_det <- reactive(
    if (input$degree != "None") {program_extract(3, "degree", input$degree)} else
    if (input$major != "None") {program_extract(3, "major", input$major)} else
    if (input$minor != "None") {program_extract(3, "minor", input$minor)} else
    if (input$specialization != "None") {program_extract(3, "specialization", input$specialization)} else
    if (input$certification != "None") {program_extract(3, "certification", input$certification)}
)

renderDT(datatable(table_prog_det(),
                   colnames = NULL,
                   rownames = FALSE,
                   options = list(
                       pageLength = 100,
                       dom = 'tip',
                       bInfo = FALSE,
                       bPaginate = FALSE
)))
```

### Requirements {data-height=800}
```{r}
table_prog_req <- reactive(
    if (input$degree != "None") {program_extract(4, "degree", input$degree)} else
    if (input$major != "None") {program_extract(4, "major", input$major)} else
    if (input$minor != "None") {program_extract(4, "minor", input$minor)} else
    if (input$specialization != "None") {program_extract(4, "specialization", input$specialization)} else
    if (input$certification != "None") {program_extract(4, "certification", input$certification)}
)

renderDT(datatable(table_prog_req(),
                   colnames = NULL,
                   rownames = FALSE,
                   options = list(
                       pageLength = 100,
                       dom = 'tip',
                       bInfo = FALSE,
                       bPaginate = FALSE
)))
```

### Credit/Course Distribution {data-height=350}
```{r}
table_prog_dis <- reactive(
    if (input$degree != "None") {program_extract_distribution("degree", input$degree)} else
    if (input$major != "None") {program_extract_distribution("major", input$major)} else
    if (input$minor != "None") {program_extract_distribution("minor", input$minor)} else
    if (input$specialization != "None") {program_extract_distribution("specialization", input$specialization)} else
    if (input$certification != "None") {program_extract_distribution("certification", input$certification)}
)

renderDT(datatable(table_prog_dis(),
                   options = list(
                       pageLength = 100,
                       dom = 'tip',
                       bInfo = FALSE,
                       bPaginate = FALSE,
                       scrollX = FALSE
)))
```

column{.tabset data-width=350}
------------

### Core courses
```{r}
table_prog_coc <- reactive(
    if (input$degree != "None") {program_extract_courses(6, "degree", input$degree)} else
    if (input$major != "None") {program_extract_courses(6, "major", input$major)} else
    if (input$minor != "None") {program_extract_courses(6, "minor", input$minor)} else
    if (input$specialization != "None") {program_extract_courses(6, "specialization", input$specialization)} else
    if (input$certification != "None") {program_extract_courses(6, "certification", input$certification)}
)

renderDT(datatable(table_prog_coc(),
                 colnames = c("Dept", "Code", "Title", "Credit", "Prereq", "Crosslist"),
                 rownames = FALSE,
                 options = list(
                     bPaginate = FALSE,
                     dom = 'Bfrtip',
                     pageLength = 100,
                     scrollY = "200px",
                     columnDefs = list(
                         list(width = '25px', targets = c(0,3)),
                         list(width = '50px', targets = c(1,4,5)),
                         list(width = '100px', targets = c(2)),
                         list(className = 'dt-center', targets = c(0,1,3))
))))
```

### Elective courses
```{r}
table_prog_elc <- reactive(
    if (input$degree != "None") {program_extract_courses(7, "degree", input$degree)} else
    if (input$major != "None") {program_extract_courses(7, "major", input$major)} else
    if (input$minor != "None") {program_extract_courses(7, "minor", input$minor)} else
    if (input$specialization != "None") {program_extract_courses(7, "specialization", input$specialization)} else
    if (input$certification != "None") {program_extract_courses(7, "certification", input$certification)}
)

renderDT(datatable(table_prog_elc(),
                 colnames = c("Dept", "Code", "Title", "Credit", "Prereq", "Crosslist"),
                 rownames = FALSE,
                 options = list(
                     bPaginate = FALSE,
                     dom = 'Bfrtip',
                     pageLength = 100,
                     scrollY = "200px",
                     columnDefs = list(
                         list(width = '25px', targets = c(0,3)),
                         list(width = '50px', targets = c(1,4,5)),
                         list(width = '100px', targets = c(2)),
                         list(className = 'dt-center', targets = c(0,1,3))
))))
```

### Course Categories (if required)
```{r}
table_prog_cat <- reactive(
    if (input$degree != "None") {program_extract(5, "degree", input$degree)} else
    if (input$major != "None") {program_extract(5, "major", input$major)} else
    if (input$minor != "None") {program_extract(5, "minor", input$minor)} else
    if (input$specialization != "None") {program_extract(5, "specialization", input$specialization)} else
    if (input$certification != "None") {program_extract(5, "certification", input$certification)}
)

renderDT(datatable(table_prog_cat(),
                   colnames = NULL,
                   rownames = FALSE,
                   options = list(
                       pageLength = 100,
                       dom = 'tip',
                       bInfo = FALSE,
                       bPaginate = FALSE
)))
```

<!------------------------------------------------------------------------------------------------->