---
title: "EmpowerX - Start Page"
date: "(`r Sys.Date()`)"
output: 
  flexdashboard::flex_dashboard:
  theme: darkly
  orientation: columns
  runtime: shiny
---

```{r initial_setup}
# libraries
## rendering
library("flexdashboard")
library("shiny")
library("DT")
## data I/O
library("googlesheets4")
## data manipulation
library("magrittr")
library("dplyr")
library("stringr")
```

<!------------------------------------------------------------------------------------------------->

Start Page
============

column{.sidebar data-width=300}
------------
### Log In

```{r}
# username
textInput(
    inputId = "username",
    label = "Username"
)

# password
textInput(
    inputId = "password",
    label = "Password"
)

# submit button
actionButton(
    inputId = "access",
    label = "Log In"
)
```

column{data-width=200}
------------
### Admission Details {data-height=300}
```{r empower_details}
# admission year
selectizeInput(
    inputId = "admission_year",
    label = "Admission Year",
    choice = "20xx"
)

# admission semester
selectizeInput(
    inputId = "admission_semester",
    label = "Admission Semester",
    choice = "FALL/SPRING"
)
```

### Program Details {data-height=700}
```{r}
# major 1
selectizeInput(
    inputId = "user_ma1",
    label = "Major 1",
    choice = "mmso"
)

# major 2
selectizeInput(
    inputId = "user_ma2",
    label = "Major 2",
    choice = "mmso"
)

# minor 1
selectizeInput(
    inputId = "user_mi1",
    label = "Minor 1",
    choice = "mmso"
)

# minor 2
selectizeInput(
    inputId = "user_mi2",
    label = "Minor 2",
    choice = "mmso"
)

# specialization 1
selectizeInput(
    inputId = "user_sp",
    label = "Speialization 1",
    choice = c("mmso", "None"),
    selected = "None"
)
```


row{data-width=250 data-height=1000}
------------

```{r}
x <- 10
y <- 25
```

### Total Degree Progress {data-height=250}
`r x` out of `r y` courses completed and `r y-x` remaining

```{r}
renderGauge({
  gauge(85, min = 0, max = 100, symbol = '%', 
        gaugeSectors(
          success = c(80, 100), warning = c(40, 79), danger = c(0, 39),
          colors = c("green", "yellow", "red")
))
})
```

### Major Progress `r reactive(input$user_ma1)` {data-height=250}
`r x` out of `r y` courses completed and `r y-x` remaining

```{r}
renderGauge({
  gauge(50, min = 0, max = 100, symbol = '%', 
        gaugeSectors(
          success = c(80, 100), warning = c(40, 79), danger = c(0, 39),
          colors = c("green", "yellow", "red")
))
})
```

### Minor Progress {data-height=250}
`r x` out of `r y` courses completed and `r y-x` remaining

```{r}
renderGauge({
  gauge(10, min = 0, max = 100, symbol = '%', 
        gaugeSectors(
          success = c(80, 100), warning = c(40, 79), danger = c(0, 39),
          colors = c("green", "yellow", "red")
))
})
```

### Specailiztion Progress {data-height=250}
Not taking a specialization

```{r}
renderGauge({
  gauge(0, min = 0, max = 100, symbol = '%', 
        gaugeSectors(
          success = c(80, 100), warning = c(40, 79), danger = c(0, 39),
          colors = c("green", "yellow", "red")
))
})
```

row{data-width=250}
------------
### Overview

Current semester = 

Current CGPA = 

Courses remaining = 

Advisor = 

### Finances